# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlIO-via-Unidecode
version:      1.01
version_from: lib/PerlIO/via/Unidecode.pm
installdirs:  site
requires:
    strict:                        0
    Text::Unidecode:               0
    utf8:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
